### ISSUE TITLE
After the last update, the admin panel stopped working

### ISSUE THREAD

**Issue by LeoBullero** [nosilver4u/ewww-image-optimizer#301]
After the last update, the admin panel stopped working, displaying a critical error message. Only disabling the plugin through the database allows for regaining access. Frontend works OK.

**Comment by nosilver4u** [comment]
Please check your server error logs, or ask you web host to do so. Not much we can do without the actual error.

**Comment by LeoBullero** [comment]
2023-06-08 15:13:30.210092 [INFO] [1104741] [T0] [195.78.67.69:48998#APVH_www.allegoria.pl:443] Abort request processing by PID:1378600, kill: 1, begin time: 1, sent time: 1, req processed: 0
2023-06-08 15:16:56.624172 [INFO] [1104741] [T0] [195.78.67.69:50998#APVH_www.allegoria.pl:443] Abort request processing by PID:1398839, kill: 1, begin time: 2, sent time: 2, req processed: 3
2023-06-08 15:17:06.890058 [INFO] [1104741] [T0] [195.78.67.69:39596#APVH_www.allegoria.pl:443] Abort request processing by PID:1399658, kill: 1, begin time: 1, sent time: 1, req processed: 1
2023-06-08 15:18:56.966045 [INFO] [1104741] [T0] [195.78.67.69:48900#APVH_www.allegoria.pl:443] Abort request processing by PID:1407076, kill: 1, begin time: 1, sent time: 1, req processed: 0
2023-06-08 15:19:01.114335 [INFO] [1104741] [T0] [195.78.67.69:53852#APVH_www.allegoria.pl:443] Abort request processing by PID:1407314, kill: 1, begin time: 1, sent time: 1, req processed: 0
2023-06-08 15:19:05.358597 [INFO] [1104741] [T0] [195.78.67.69:54154#APVH_www.allegoria.pl:443] Abort request processing by PID:1407785, kill: 1, begin time: 1, sent time: 1, req processed: 0
2023-06-08 15:20:55.051155 [INFO] [1104741] [T0] [195.78.67.69:48986#APVH_www.allegoria.pl:443] Abort request processing by PID:1422887, kill: 1, begin time: 2, sent time: 2, req processed: 1
2023-06-08 15:20:56.602785 [INFO] [1104741] [T0] [195.78.67.69:49010#APVH_www.allegoria.pl:443] Abort request processing by PID:1423170, kill: 1, begin time: 1, sent time: 1, req processed: 0
2023-06-08 15:20:57.990796 [INFO] [1104741] [T0] [195.78.67.69:49092#APVH_www.allegoria.pl:443] Abort request processing by PID:1423277, kill: 1, begin time: 1, sent time: 1, req processed: 0
2023-06-08 15:21:00.987164 [INFO] [1104741] [T0] [195.78.67.69:38714#APVH_www.allegoria.pl:443] Abort request processing by PID:1423387, kill: 1, begin time: 1, sent time: 1, req processed: 1
2023-06-08 15:21:02.916673 [INFO] [1104741] [T0] [195.78.67.69:38898#APVH_www.allegoria.pl:443] Abort request processing by PID:1423741, kill: 1, begin time: 1, sent time: 1, req processed: 0
2023-06-08 15:23:03.422425 [INFO] [1104741] [T0] [195.78.67.69:48244#APVH_www.allegoria.pl:443] Abort request processing by PID:1430931, kill: 1, begin time: 1, sent time: 1, req processed: 0
2023-06-08 15:23:08.440336 [INFO] [1104741] [T0] [195.78.67.69:48464#APVH_www.allegoria.pl:443] Abort request processing by PID:1431244, kill: 1, begin time: 1, sent time: 1, req processed: 0
2023-06-08 15:25:03.487894 [INFO] [1104741] [T0] [195.78.67.69:56948#APVH_www.allegoria.pl:443] [ACL] Access to context [/wp-content/uploads/woocommerce_uploads/] is denied!
2023-06-08 15:25:03.567780 [NOTICE] [1104741] [T0] [83.144.93.166:37121-H3:1EAEA232E75909F6-48#APVH_www.allegoria.pl:443] [STDERR] WordPress database error Multiple primary key defined for query ALTER TABLE wp_wc_gpf_render_cache CHANGE COLUMN `id` `id` bigint unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY made by activate_plugins, activate_plugin, do_action('activate_woocommerce-product-feeds/woocommerce-gpf.php'), WP_Hook->do_action, WP_Hook->apply_filters, woocommerce_gpf_install, dbDelta\n
2023-06-08 15:28:34.781219 [INFO] [1104741] [T0] [51.178.146.199:41782#APVH_www.allegoria.pl:443] [ACL] Access to context [/] is denied!
2023-06-08 15:33:30.743925 [INFO] [1104741] [T0] [83.144.93.166:51952-H3:62A45F11345498DC-0#APVH_www.allegoria.pl:443] Abort request processing by PID:1492120, kill: 1, begin time: 7, sent time: 7, req processed: 0
2023-06-08 15:37:02.346491 [NOTICE] [1104741] [T0] [83.144.93.166:60824-H3:E189C3B2E1A24D11-4#APVH_www.allegoria.pl:443] [STDERR] WordPress database error Multiple primary key defined for query ALTER TABLE wp_wc_gpf_render_cache CHANGE COLUMN `id` `id` bigint unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY made by activate_plugins, activate_plugin, do_action('activate_woocommerce-product-feeds/woocommerce-gpf.php'), WP_Hook->do_action, WP_Hook->apply_filters, woocommerce_gpf_install, dbDelta\n
2023-06-08 15:40:35.207065 [NOTICE] [1104741] [T0] [83.144.93.166:36739-H3:68C4B86D95CA8877-8#APVH_www.allegoria.pl:443] [STDERR] WordPress database error Multiple primary key defined for query ALTER TABLE wp_wc_gpf_render_cache CHANGE COLUMN `id` `id` bigint unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY made by activate_plugins, activate_plugin, do_action('activate_woocommerce-product-feeds/woocommerce-gpf.php'), WP_Hook->do_action, WP_Hook->apply_filters, woocommerce_gpf_install, dbDelta\n
2023-06-08 15:44:49.362622 [NOTICE] [1104741] [T0] [83.144.93.166:54213-H3:C5927049DBA05B1B-16#APVH_www.allegoria.pl:443] [STDERR] WordPress database error Multiple primary key defined for query ALTER TABLE wp_wc_gpf_render_cache CHANGE COLUMN `id` `id` bigint unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY made by activate_plugins, activate_plugin, do_action('activate_woocommerce-product-feeds/woocommerce-gpf.php'), WP_Hook->do_action, WP_Hook->apply_filters, woocommerce_gpf_install, dbDelta\n
2023-06-08 15:44:53.857910 [INFO] [1104741] [T0] [83.144.93.166:54213-H3:C5927049DBA05B1B-20#APVH_www.allegoria.pl:443] Abort request processing by PID:1560935, kill: 1, begin time: 1, sent time: 1, req processed: 1
2023-06-08 15:46:16.276139 [INFO] [1104741] [T0] [83.144.93.166:54213-H3:C5927049DBA05B1B-792#APVH_www.allegoria.pl:443] Abort request processing by PID:1574189, kill: 1, begin time: 1, sent time: 1, req processed: 0
2023-06-08 15:46:37.404404 [INFO] [1104741] [T0] [195.78.67.69:40380#APVH_www.allegoria.pl:443] Abort request processing by PID:1575456, kill: 1, begin time: 1, sent time: 1, req processed: 0
2023-06-08 15:50:08.980111 [INFO] [1104741] [T0] [195.78.67.69:49152#APVH_www.allegoria.pl:443] Abort request processing by PID:1596968, kill: 1, begin time: 1, sent time: 1, req processed: 1
2023-06-08 15:50:10.171930 [INFO] [1104741] [T0] [195.78.67.69:60368#APVH_www.allegoria.pl:443] Abort request processing by PID:1597547, kill: 1, begin time: 1, sent time: 1, req processed: 0
2023-06-08 15:51:15.525511 [INFO] [1104741] [T0] [195.78.67.69:35914#APVH_www.allegoria.pl:443] Abort request processing by PID:1601939, kill: 1, begin time: 1, sent time: 1, req processed: 0
2023-06-08 15:51:57.942509 [INFO] [1104741] [T0] [195.78.67.69:50038#APVH_www.allegoria.pl:443] Abort request processing by PID:1604479, kill: 1, begin time: 1, sent time: 1, req processed: 0
2023-06-08 15:56:36.927654 [INFO] [1104741] [T0] [195.78.67.69:35312#APVH_www.allegoria.pl:443] Abort request processing by PID:1631524, kill: 1, begin time: 1, sent time: 1, req processed: 1
2023-06-08 15:59:15.099807 [INFO] [1104741] [T0] [195.78.67.69:37900#APVH_www.allegoria.pl:443] Abort request processing by PID:1642808, kill: 1, begin time: 2, sent time: 2, req processed: 0
2023-06-08 15:59:16.794361 [INFO] [1104741] [T0] [195.78.67.69:37980#APVH_www.allegoria.pl:443] Abort request processing by PID:1642929, kill: 1, begin time: 1, sent time: 1, req processed: 0

**Comment by nosilver4u** [comment]
There's nothing in there from EWWW IO. Have the logs been rotated since you had the issue with EWWW IO? Otherwise, it might be some other plugin, though I don't think those db errors usually are "fatal" either and I don't see anything in that log to explain a broken admin panel. WP will typically also try to send an email to the admin address with the error message, so you might check for that also.

**Comment by LeoBullero** [comment]
Thank you for your prompt reply. Staging works, pehaps it is a conflict with the caching plugins. We will investigate it today.

**Comment by LeoBullero** [comment]
We found the fatal error trying to check the setting of the plugin:

[17-Jun-2023 12:05:12 UTC] PHP Fatal error:  Uncaught WpOrg\Requests\Exception\InvalidArgument: WpOrg\Requests\Cookie::__construct(): Argument #1 ($name) must be of type string, integer given in /home/allegoryk/domains/allegoryk.cfolks.pl/public_html/wp-includes/Requests/src/Exception/InvalidArgument.php:29
Stack trace:
#0 /home/allegoryk/domains/allegoryk.cfolks.pl/public_html/wp-includes/Requests/src/Cookie.php(83): WpOrg\Requests\Exception\InvalidArgument::create(1, '$name', 'string', 'integer')
#1 /home/allegoryk/domains/allegoryk.cfolks.pl/public_html/wp-includes/class-wp-http.php(472): WpOrg\Requests\Cookie->__construct(135370, '')
#2 /home/allegoryk/domains/allegoryk.cfolks.pl/public_html/wp-includes/class-wp-http.php(352): WP_Http::normalize_cookies(Array)
#3 /home/allegoryk/domains/allegoryk.cfolks.pl/public_html/wp-includes/class-wp-http.php(616): WP_Http->request('https://allegor...', Array)
#4 /home/allegoryk/domains/allegoryk.cfolks.pl/public_html/wp-includes/http.php(179): WP_Http->post('https://allegor...', Array)
#5 /home/allegoryk/domains/allegoryk.cfolks.pl/public_html/wp-content/plugins/ewww-image-optimizer/common.php(11271): wp_remote_post('https://allegor...', Array)
#6 /home/allegoryk/domains/allegoryk.cfolks.pl/public_html/wp-content/plugins/ewww-image-optimizer/common.php(11968): ewwwio_debug_info()
#7 /home/allegoryk/domains/allegoryk.cfolks.pl/public_html/wp-includes/class-wp-hook.php(308): ewww_image_optimizer_options('')
#8 /home/allegoryk/domains/allegoryk.cfolks.pl/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#9 /home/allegoryk/domains/allegoryk.cfolks.pl/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#10 /home/allegoryk/domains/allegoryk.cfolks.pl/public_html/wp-admin/admin.php(259): do_action('settings_page_e...')
#11 /home/allegoryk/domains/allegoryk.cfolks.pl/public_html/wp-admin/options-general.php(10): require_once('/home/allegoryk...')
#12 {main}
  thrown in /home/allegoryk/domains/allegoryk.cfolks.pl/public_html/wp-includes/Requests/src/Exception/InvalidArgument.php on line 29

**Comment by nosilver4u** [comment]
Hi, thanks for providing that, unfortunately it is a bug in WordPress core, and isn't even remotely new code in EWWW IO. Even though it happens to be triggered by EWWW IO, the normalize_cookies() method in the WP code should convert the cookie name to a string value since the Requests library requires a string.
Now, this also points out something kind of weird, since EWWW IO is merely passing along your existing cookies in the test async request, which is that your browser has a cookie with an integer name. If you're using Chrome and are familiar with the dev console, you could open that and go to the Applications tab to inspect your cookies--and potentially delete the offending one to see what happens.
I've reported it upstream, and you can track what happens here: https://core.trac.wordpress.org/ticket/58566#ticket

**Comment by LeoBullero** [comment]
The identical problem, regarding the Site Health plugin, is described here: https://wordpress.org/support/topic/php-fatal-error-class-wp-site-health-php/#post-16826663.

**Comment by nosilver4u** [comment]
Yup, that's the same bug alright. I believe the Requests library was updated in WP 6.2 to work towards PHP 8.1/8.2 compatibility, which likely introduced the stricter type checks.
